"""initial schema

Revision ID: 23ecc1bba190
Revises: 
Create Date: 2026-07-16 13:43:40.435826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23ecc1bba190'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('steam_app_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('regular_price', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('header_image_url', sa.String(), nullable=True),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('price_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steam_app_id')
    )
    op.create_table('pack_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stripe_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stripe_event_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('received', 'processed', 'failed', name='stripe_event_status'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_event_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), nullable=False),
    sa.Column('age_attested', sa.Boolean(), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_connect_account_id', sa.String(), nullable=True),
    sa.Column('wallet_balance_cached', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('deposit', 'pack_purchase', 'buyback_credit', 'withdrawal', 'refund', 'admin_adjustment', name='ledger_entry_type'), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('odds_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pack_type_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pack_type_id'], ['pack_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', name='withdrawal_status'), nullable=False),
    sa.Column('stripe_payout_id', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds_bands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('odds_table_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('probability', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('min_price', sa.BigInteger(), nullable=False),
    sa.Column('max_price', sa.BigInteger(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['odds_table_id'], ['odds_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pack_type_id', sa.UUID(), nullable=False),
    sa.Column('odds_table_id', sa.UUID(), nullable=False),
    sa.Column('price_paid', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('unopened', 'opened', name='pack_status'), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['odds_table_id'], ['odds_tables.id'], ),
    sa.ForeignKeyConstraint(['pack_type_id'], ['pack_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pulls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pack_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('odds_band_id', sa.UUID(), nullable=False),
    sa.Column('locked_value', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('vaulted', 'bought_back', 'redeem_requested', 'redeemed', name='pull_status'), nullable=False),
    sa.Column('roll_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['odds_band_id'], ['odds_bands.id'], ),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_id')
    )
    op.create_table('redemption_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pull_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'fulfilled', 'cancelled', name='redemption_status'), nullable=False),
    sa.Column('delivered_key', sa.String(), nullable=True),
    sa.Column('fulfilled_by', sa.UUID(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fulfilled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pull_id'], ['pulls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pull_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redemption_requests')
    op.drop_table('pulls')
    op.drop_table('packs')
    op.drop_table('odds_bands')
    op.drop_table('withdrawals')
    op.drop_table('odds_tables')
    op.drop_table('ledger_entries')
    op.drop_table('users')
    op.drop_table('stripe_events')
    op.drop_table('pack_types')
    op.drop_table('games')
    # ### end Alembic commands ###
